---
root: true
parser: babel-eslint
parserOptions:
  sourceType: module
extends: standard
settings:
  import/resolver: webpack
env:
  node: true
rules:
  max-len:
    - warn
    - code: 100
      ignoreUrls: true
  no-var: error
  prefer-const:
    - error
    - destructuring: all
      ignoreReadBeforeAssign: true
  no-restricted-imports:
    - error
    - lodash
    - underscore
